#!/usr/bin/env Rscript
# ============================================================================
# Compliance batch-evaluation speed bench — fixed-input, bit-identical
# correctness gate.
#
# Purpose: give a `/goal` loop an unambiguous, reward-hack-resistant signal for
# behavior-preserving (Class A) speedups of the COMPLIANCE-ENGINE batch hot
# path — `evaluate_compliance(..., precomputed = TRUE)` and everything it calls
# (`calculate_district_capacity()` + the 18 `calculate_*` unit-capacity
# functions + `summarize`). This path has ZERO randomness, so a correct speedup
# LOWERS the time while keeping the output hash EQUAL to the captured baseline.
#
# It loads one municipality once, pre-computes the (cheap) station-area overlap
# once, then times N_ITERS evaluations over a FIXED, deterministic grid of
# zoning-parameter sets, and reports:
#   ELAPSED       min wall-clock of the N_ITERS-iteration batch loop (s)
#   OUTPUT_HASH   rlang::hash of every iteration's per-parcel results + summary
#   HASH_MATCH    OUTPUT_HASH == baseline hash (the correctness gate)
#   SPEEDUP       baseline_elapsed / ELAPSED
#
# Determinism is self-checked: the two runs must hash equal, or the bench FAILs
# (this path is RNG-free, so any disagreement is a correctness bug).
#
# WHY station-only precompute: the density-denominator step is a single sum()
# whether or not deductions are precomputed (compliance_pipeline.R:1289-1304),
# so the timed loop stays pure arithmetic without the ~12-min density
# st_intersection. The gross-density denominator falls back to total area here;
# that does not change what the bench measures (the per-iteration compute path).
#
# SCOPE for an optimizer: edit the per-iteration compute path only
# (compliance_pipeline.R, unit_capacity_calculations.R, and precomputed=TRUE
# branches of gis_operations.R). Do NOT edit the one-time setup functions
# (load_municipality, precompute_spatial_attributes, load_transit_stations) —
# they are this bench's fixed input, not the thing under test.
#
# Usage:
#   Rscript dev/bench/compliance_bench.R              # measure + compare
#   Rscript dev/bench/compliance_bench.R --capture    # (re)write baseline
#
# DO NOT EDIT this file, compliance_baseline.txt, N_ITERS, the municipality, or
# the parameter grid while a speed goal is active — they define the measurement.
# ============================================================================

suppressMessages({ library(sf) })

# --- fixed measurement parameters (treat as frozen) -------------------------
PKG_ROOT   <- Sys.getenv("MBTAZONE_PACKAGE_ROOT", unset = "/home/dhidalgo/projects/mbtazone")
PARCEL_ZIP <- file.path(PKG_ROOT, "inst/extdata/parcels/49_CAMBRIDGE_basic.zip")
COMMUNITY  <- "Cambridge"
N_ITERS    <- 60L      # ~0.32 s/iter on 12,867 parcels -> ~19 s baseline
RUNS       <- 2L       # repeats; ELAPSED = min, hashes must agree
BASELINE   <- file.path(PKG_ROOT, "dev", "bench", "compliance_baseline.txt")

setwd(PKG_ROOT)
suppressMessages(pkgload::load_all(PKG_ROOT, quiet = TRUE,
                                   helpers = FALSE, attach_testthat = FALSE))

# --- one-time setup (untimed): load parcels + cheap station precompute -------
stopifnot("parcel zip missing" = file.exists(PARCEL_ZIP))
parcels  <- load_municipality(PARCEL_ZIP, community_name = COMMUNITY)
stations <- load_transit_stations()
parcels  <- precompute_spatial_attributes(parcels = parcels,
                                          station_areas = stations,
                                          verbose = FALSE)
parcels$district_id <- "D1"   # single-district batch (the common case)

# --- fixed deterministic parameter grid (no RNG) ----------------------------
# Modular cycling over each field gives N_ITERS distinct sets where different
# constraints bind across iterations, exercising the min()/fcase branches.
build_param_sets <- function(n) {
  bh   <- c(2, 3, 4, 5, 6)
  far  <- c(0.5, 1.0, 1.5, 2.0)
  mls  <- c(3000, 5000, 7500, 10000)
  dua  <- c(15, 20, 25)
  cov  <- c(0.4, 0.6, 0.8)
  lapdu <- c(NA_real_, 1500, 2000)
  pick <- function(v, i) v[((i - 1L) %% length(v)) + 1L]
  lapply(seq_len(n), function(i) create_zoning_parameters(
    min_lot_size                     = pick(mls, i),
    building_height                  = pick(bh, i),
    FAR                              = pick(far, i),
    max_lot_coverage                 = pick(cov, i),
    max_dwelling_units_per_acre      = pick(dua, i),
    lot_area_per_dwelling_unit       = pick(lapdu, i),
    parking_spaces_per_dwelling_unit = 1,
    min_required_open_space          = 0.2
  ))
}
param_sets <- build_param_sets(N_ITERS)

run_once <- function() {
  out <- vector("list", N_ITERS)
  for (i in seq_len(N_ITERS)) {
    res <- suppressMessages(evaluate_compliance(
      municipality = parcels, districts = "district_id",
      zoning_params = param_sets[[i]], community_type = "rapid_transit",
      custom_requirements = list(min_units = 100, min_acres = 5),
      precomputed = TRUE, verbose = FALSE))
    out[[i]] <- list(parcels = sf::st_drop_geometry(res$parcel_detail),
                     summary = res$summary)
  }
  out
}

elapsed <- numeric(RUNS); hashes <- character(RUNS)
for (i in seq_len(RUNS)) {
  t <- system.time(o <- run_once())[["elapsed"]]
  elapsed[i] <- t; hashes[i] <- rlang::hash(o)
}

deterministic <- length(unique(hashes)) == 1L
this_elapsed  <- min(elapsed)
this_hash     <- hashes[[1]]

# --- capture mode: write baseline and exit ----------------------------------
args <- commandArgs(trailingOnly = TRUE)
if ("--capture" %in% args) {
  git_hash <- tryCatch(trimws(system("git rev-parse --short HEAD", intern = TRUE)),
                       error = function(e) "unknown")
  writeLines(c(
    sprintf("baseline_hash=%s", this_hash),
    sprintf("baseline_elapsed=%.3f", this_elapsed),
    sprintf("municipality=%s", COMMUNITY),
    sprintf("n_iters=%d", N_ITERS),
    sprintf("git_commit=%s", git_hash)
  ), BASELINE)
  cat(sprintf("\nBASELINE CAPTURED -> %s\n", BASELINE))
  cat(sprintf("baseline_hash=%s\nbaseline_elapsed=%.3f\ndeterministic=%s\n",
              this_hash, this_elapsed, deterministic))
  quit(save = "no")
}

# --- compare mode -----------------------------------------------------------
base <- if (file.exists(BASELINE)) {
  kv <- strsplit(readLines(BASELINE), "=")
  setNames(vapply(kv, `[`, "", 2), vapply(kv, `[`, "", 1))
} else NULL

cat(sprintf("\n=== COMPLIANCE BATCH BENCH (%s, n_iters=%d, runs=%d) ===\n",
            COMMUNITY, N_ITERS, RUNS))
cat(sprintf("ELAPSED: %.2f\n", this_elapsed))
cat(sprintf("OUTPUT_HASH: %s\n", this_hash))
cat(sprintf("DETERMINISTIC: %s\n", deterministic))
if (!is.null(base)) {
  base_hash <- base[["baseline_hash"]]; base_el <- as.numeric(base[["baseline_elapsed"]])
  hash_match <- identical(this_hash, base_hash)
  cat(sprintf("BASELINE_HASH: %s\n", base_hash))
  cat(sprintf("BASELINE_ELAPSED: %.2f\n", base_el))
  cat(sprintf("HASH_MATCH: %s\n", hash_match))
  cat(sprintf("SPEEDUP: %.3fx\n", base_el / this_elapsed))
  if (!deterministic)
    cat("NOTE: non-deterministic output across runs — this is a correctness bug.\n")
} else {
  cat("BASELINE: (none — run with --capture first)\n")
}
