#!/usr/bin/env Rscript
# ============================================================================
# LCC discovery speed bench — fixed-seed, bit-identical correctness gate.
#
# Purpose: give a `/goal` loop an unambiguous, reward-hack-resistant signal for
# behavior-preserving (Class A) speedups of the LCC DISCOVERY tier — the
# pipeline stage (Tier 3A in inst/targets/_targets.R) that builds
# `discovered_lcc_library` from the parcel graph, BEFORE the MCMC sampler runs.
# It exercises the heavy discovery hotspots: spanning-tree cut enumeration
# (discover_lccs_from_trees), BFS boundary + capacity-band growth
# (run_bfs_lcc_supplement, discover_lccs_single_band -> bfs_grow_block), and
# the deterministic library assembly (combine_* + build_lcc_library_from_tree_
# discovery: coverage selection, igraph attribute extraction, neighbor index).
#
# This tier draws random numbers (tree sampling, BFS target capacities), so the
# gate is the SAME kind as the MCMC sampler bench: under a fixed seed the whole
# discovery is reproducible, and a correct speedup LOWERS the time while keeping
# the output hash EQUAL to the captured baseline. The two runs must hash equal
# (DETERMINISTIC) or the bench FAILs — an optimization that introduced
# nondeterminism is a bug, not a speedup.
#
# It loads a pre-built warm targets store (no gpkg / pipeline rebuild needed) for
# the two fixed inputs the discovery consumes — `parcel_graph_result` and
# `constraints` — then runs the full LCC discovery chain TWICE with a fixed seed
# and reports:
#   ELAPSED       min wall-clock of one full discovery run (s)
#   OUTPUT_HASH   rlang::hash of the discovered_lcc_library
#   HASH_MATCH    OUTPUT_HASH == baseline hash (the correctness gate)
#   SPEEDUP       baseline_elapsed / ELAPSED
#
# The pipeline runs the five capacity bands as PARALLEL crew workers; this bench
# runs them SERIALLY in one process under one seed. That is intentional: the
# bench defines its OWN baseline from current code — it does not need to match
# the pipeline's stored library, only to exercise the real discovery code and be
# internally reproducible. The serial single-seed draw sequence is the thing the
# Class A fence must preserve.
#
# Usage:
#   Rscript dev/bench/discovery_bench.R              # measure + compare to baseline
#   Rscript dev/bench/discovery_bench.R --capture    # (re)write discovery_baseline.txt
#
# DO NOT EDIT this file, discovery_baseline.txt, the seed, the store, or the
# discovery size constants in inst/targets/temp_targets_*.R while a speed goal is
# active — they define the measurement. The optimization target is the discovery
# implementation in R/mcmc_spanning_tree.R and R/mcmc_parcel_library.R.
# ============================================================================

suppressMessages({ library(targets); library(igraph) })

# --- fixed measurement parameters (treat as frozen) -------------------------
PKG_ROOT <- Sys.getenv("MBTAZONE_PACKAGE_ROOT",
  unset = "/home/dhidalgo/projects/mbtazone")
STORE    <- file.path(PKG_ROOT, "ext", "_targets_Topsfield")
SEED     <- 42L
RUNS     <- 2L         # repeats; ELAPSED = min, hashes must agree
BASELINE <- file.path(PKG_ROOT, "dev", "bench", "discovery_baseline.txt")

setwd(PKG_ROOT)
suppressMessages(pkgload::load_all(PKG_ROOT, quiet = TRUE,
                                   helpers = FALSE, attach_testthat = FALSE))
# Discovery size constants are plain top-level objects in these config files
# (n_trees, BFS sample counts, capacity bands, library cap). Sourcing them here
# mirrors the pipeline; they are FROZEN inputs to the measurement, not targets.
source(file.path(PKG_ROOT, "inst/targets/temp_targets_config.R"))
source(file.path(PKG_ROOT, "inst/targets/temp_targets_parcel_config.R"))

stopifnot("warm store missing" = dir.exists(STORE))
tar_load(c(parcel_graph_result, constraints), store = STORE)

# --- one full LCC discovery (Tier 3A of inst/targets/_targets.R) -------------
# Reproduces the target chain tree_discovered_lccs -> bfs_discovered_lccs ->
# {per-band discovery} -> bfs_stratified_lccs -> combined_discovered_lccs ->
# discovered_lcc_library, serially, under one seed.
run_once <- function() {
  set.seed(SEED)
  pg <- parcel_graph_result$parcel_graph

  # Stage 1: tree enumeration (Wilson's algorithm) — RNG
  tree_lccs <- discover_lccs_from_trees(
    parcel_graph           = pg,
    constraints            = constraints,
    n_trees                = TREE_LCC_N_TREES,
    forbidden_parcels      = NULL,
    max_discovery_capacity = constraints$min_capacity * DISCOVERY_CAPACITY_MULTIPLIER,
    verbose                = FALSE
  )

  # Stage 2a: BFS boundary supplement — RNG
  bfs_lccs <- run_bfs_lcc_supplement(
    tree_discovered_lccs = tree_lccs,
    parcel_graph         = pg,
    constraints          = constraints,
    n_samples            = BFS_LCC_N_SAMPLES,
    n_seeds              = BFS_LCC_N_SEEDS,
    forbidden_parcels    = NULL,
    verbose              = FALSE
  )

  existing_keys <- c(
    tree_lccs$discovered_lccs$lcc_key,
    bfs_lccs$discovered_lccs$lcc_key
  )

  # Stage 2b: capacity-stratified BFS — RNG. Pipeline parallelises these bands
  # across crew workers; the bench runs them serially (see header).
  band_results <- lapply(seq_along(LCC_CAPACITY_BANDS_RELATIVE), function(b) {
    discover_lccs_single_band(
      parcel_graph            = pg,
      constraints             = constraints,
      band_idx                = b,
      capacity_bands_relative = LCC_CAPACITY_BANDS_RELATIVE,
      samples_per_band        = LCC_BAND_SAMPLES_PER_BAND,
      max_attempts_per_band   = LCC_BAND_MAX_ATTEMPTS,
      forbidden_parcels       = NULL,
      existing_keys           = existing_keys,
      verbose                 = FALSE
    )
  })
  bfs_stratified <- combine_stratified_band_results(band_results)

  # Stage 3: combine all discoveries — deterministic
  combined <- combine_all_lcc_discoveries(
    tree_discovered = tree_lccs,
    bfs_discovered  = bfs_lccs,
    bfs_stratified  = bfs_stratified,
    verbose         = FALSE
  )

  # Stage 4: build library (coverage selection, attribute extraction, neighbor
  # index) — deterministic
  build_lcc_library_from_tree_discovery(
    combined$discovered_blocks,
    pg,
    constraints      = constraints,
    max_library_size = LCC_LIBRARY_MAX_SIZE,
    bfs_reservation  = BFS_RESERVATION_LCC
  )
}

elapsed <- numeric(RUNS); hashes <- character(RUNS)
for (i in seq_len(RUNS)) {
  t <- system.time(s <- suppressMessages(run_once()))[["elapsed"]]
  elapsed[i] <- t; hashes[i] <- rlang::hash(s)
}

deterministic <- length(unique(hashes)) == 1L
this_elapsed  <- min(elapsed)
this_hash     <- hashes[[1]]

# --- capture mode: write baseline and exit ----------------------------------
args <- commandArgs(trailingOnly = TRUE)
if ("--capture" %in% args) {
  git_hash <- tryCatch(trimws(system("git rev-parse --short HEAD", intern = TRUE)),
                       error = function(e) "unknown")
  writeLines(c(
    sprintf("baseline_hash=%s", this_hash),
    sprintf("baseline_elapsed=%.3f", this_elapsed),
    sprintf("store=%s", basename(STORE)),
    sprintf("seed=%d", SEED),
    sprintf("git_commit=%s", git_hash)
  ), BASELINE)
  cat(sprintf("\nBASELINE CAPTURED -> %s\n", BASELINE))
  cat(sprintf("baseline_hash=%s\nbaseline_elapsed=%.3f\ndeterministic=%s\n",
              this_hash, this_elapsed, deterministic))
  quit(save = "no")
}

# --- compare mode -----------------------------------------------------------
base <- if (file.exists(BASELINE)) {
  kv <- strsplit(readLines(BASELINE), "=")
  setNames(vapply(kv, `[`, "", 2), vapply(kv, `[`, "", 1))
} else NULL

cat(sprintf("\n=== LCC DISCOVERY SPEED BENCH (%s, seed=%d, runs=%d) ===\n",
            basename(STORE), SEED, RUNS))
cat(sprintf("ELAPSED: %.2f\n", this_elapsed))
cat(sprintf("OUTPUT_HASH: %s\n", this_hash))
cat(sprintf("DETERMINISTIC: %s\n", deterministic))
if (!is.null(base)) {
  base_hash <- base[["baseline_hash"]]; base_el <- as.numeric(base[["baseline_elapsed"]])
  hash_match <- identical(this_hash, base_hash)
  cat(sprintf("BASELINE_HASH: %s\n", base_hash))
  cat(sprintf("BASELINE_ELAPSED: %.2f\n", base_el))
  cat(sprintf("HASH_MATCH: %s\n", hash_match))
  cat(sprintf("SPEEDUP: %.3fx\n", base_el / this_elapsed))
  if (!deterministic)
    cat("NOTE: non-deterministic output across runs — this is a correctness bug.\n")
} else {
  cat("BASELINE: (none — run with --capture first)\n")
}
