#!/usr/bin/env Rscript
# ============================================================================
# Parcel graph construction speed bench — fixed-input, bit-identical gate.
#
# Purpose: give a `/goal` loop an unambiguous, reward-hack-resistant signal for
# behavior-preserving (Class A) speedups of the PARCEL GRAPH CONSTRUCTION tier —
# the pipeline stage (Tier 2 in inst/targets/_targets.R) that turns the loaded
# district geometry into the adjacency graph every later tier consumes:
#   adjacency_graph     <- build_adjacency_graph(geometry, right_of_way, ...)
#   parcel_graph_result <- build_identity_parcel_graph(adjacency_graph)   # MACRO_SCALE == 0
# build_adjacency_graph is the spatial heavy lifter (st_buffer -> st_intersects
# candidate generation -> st_distance edge filtering -> right-of-way crossing
# detection -> igraph assembly).
#
# This tier draws NO random numbers (the MACRO_SCALE == 0 identity branch is a
# pure mapping; build_adjacency_graph is pure geometry), so the gate is the SAME
# kind as the compliance batch bench: a correct speedup LOWERS the time while
# keeping the output hash EQUAL to the captured baseline. The two runs must hash
# equal (DETERMINISTIC) — this path is RNG-free, so any disagreement is a bug
# (e.g. an optimization that introduced parallel nondeterminism).
#
# It loads a pre-built warm targets store (no gpkg / pipeline rebuild needed) for
# the one fixed input the tier consumes — `district_data` (its $district_geometry
# and $district_right_of_way) — then rebuilds the graph TWICE and reports:
#   ELAPSED       min wall-clock of one full Tier-2 build (s)
#   OUTPUT_HASH   rlang::hash of as_data_frame(parcel_graph, what = "both")
#   HASH_MATCH    OUTPUT_HASH == baseline hash (the correctness gate)
#   SPEEDUP       baseline_elapsed / ELAPSED
#
# The graph object is hashed via its canonical vertex+edge data frames (not the
# raw igraph object) so the gate is over graph CONTENT — names, vertex attributes
# (capacity/area/centroids/station overlap), and the edge list with is_row_crossing
# — independent of any incidental igraph-internal representation.
#
# Usage:
#   Rscript dev/bench/graph_bench.R              # measure + compare to baseline
#   Rscript dev/bench/graph_bench.R --capture    # (re)write graph_baseline.txt
#
# DO NOT EDIT this file, graph_baseline.txt, the store, or the tier-2 constants
# (MAX_DIST_FEET, MIN_COVERAGE_RATIO, MACRO_SCALE) in inst/targets/temp_targets_*.R
# while a speed goal is active — they define the measurement. The optimization
# target is the construction implementation in R/mcmc_graph_building.R and
# R/mcmc_parcel_construction.R.
# ============================================================================

suppressMessages({ library(targets); library(igraph) })

# --- fixed measurement parameters (treat as frozen) -------------------------
PKG_ROOT <- Sys.getenv("MBTAZONE_PACKAGE_ROOT",
  unset = "/home/dhidalgo/projects/mbtazone")
STORE    <- file.path(PKG_ROOT, "ext", "_targets_Topsfield")
SEED     <- 42L        # RNG-free path; set for safety only
RUNS     <- 2L         # repeats; ELAPSED = min, hashes must agree
BASELINE <- file.path(PKG_ROOT, "dev", "bench", "graph_baseline.txt")

setwd(PKG_ROOT)
suppressMessages(pkgload::load_all(PKG_ROOT, quiet = TRUE,
                                   helpers = FALSE, attach_testthat = FALSE))
# Tier-2 constants are plain top-level objects in these config files. Sourcing
# them here mirrors the pipeline; they are FROZEN inputs to the measurement.
source(file.path(PKG_ROOT, "inst/targets/temp_targets_config.R"))
source(file.path(PKG_ROOT, "inst/targets/temp_targets_parcel_config.R"))

stopifnot("warm store missing" = dir.exists(STORE))
tar_load(district_data, store = STORE)

# --- one full Tier-2 build (inst/targets/_targets.R) -------------------------
# Reproduces adjacency_graph -> parcel_graph_result under the frozen constants.
# MACRO_SCALE == 0 selects the identity mapping (raw parcels), matching the
# single-zone pipeline configuration.
run_once <- function() {
  set.seed(SEED)
  adjacency_graph <- build_adjacency_graph(
    geometry_sf        = district_data$district_geometry,
    right_of_way_sf    = district_data$district_right_of_way,
    max_dist_ft        = MAX_DIST_FEET,
    min_coverage_ratio = MIN_COVERAGE_RATIO,
    verbose            = FALSE
  )
  if (MACRO_SCALE == 0) {
    build_identity_parcel_graph(adjacency_graph)
  } else {
    build_parcel_graph_target(
      adjacency_graph,
      target_area_min  = MACRO_BASE_AREA_MIN * MACRO_SCALE,
      target_area_max  = MACRO_BASE_AREA_MAX * MACRO_SCALE,
      atomic_threshold = MACRO_ATOMIC_THRESHOLD,
      seed             = 123
    )
  }
}

# Canonical, representation-independent digest of the constructed graph.
graph_digest <- function(result) {
  pg <- result$parcel_graph
  igraph::as_data_frame(pg, what = "both")
}

elapsed <- numeric(RUNS); hashes <- character(RUNS)
for (i in seq_len(RUNS)) {
  t <- system.time(s <- suppressMessages(run_once()))[["elapsed"]]
  elapsed[i] <- t; hashes[i] <- rlang::hash(graph_digest(s))
}

deterministic <- length(unique(hashes)) == 1L
this_elapsed  <- min(elapsed)
this_hash     <- hashes[[1]]

# --- capture mode: write baseline and exit ----------------------------------
args <- commandArgs(trailingOnly = TRUE)
if ("--capture" %in% args) {
  git_hash <- tryCatch(trimws(system("git rev-parse --short HEAD", intern = TRUE)),
                       error = function(e) "unknown")
  writeLines(c(
    sprintf("baseline_hash=%s", this_hash),
    sprintf("baseline_elapsed=%.3f", this_elapsed),
    sprintf("store=%s", basename(STORE)),
    sprintf("git_commit=%s", git_hash)
  ), BASELINE)
  cat(sprintf("\nBASELINE CAPTURED -> %s\n", BASELINE))
  cat(sprintf("baseline_hash=%s\nbaseline_elapsed=%.3f\ndeterministic=%s\n",
              this_hash, this_elapsed, deterministic))
  quit(save = "no")
}

# --- compare mode -----------------------------------------------------------
base <- if (file.exists(BASELINE)) {
  kv <- strsplit(readLines(BASELINE), "=")
  setNames(vapply(kv, `[`, "", 2), vapply(kv, `[`, "", 1))
} else NULL

cat(sprintf("\n=== PARCEL GRAPH CONSTRUCTION BENCH (%s, runs=%d) ===\n",
            basename(STORE), RUNS))
cat(sprintf("ELAPSED: %.2f\n", this_elapsed))
cat(sprintf("OUTPUT_HASH: %s\n", this_hash))
cat(sprintf("DETERMINISTIC: %s\n", deterministic))
if (!is.null(base)) {
  base_hash <- base[["baseline_hash"]]; base_el <- as.numeric(base[["baseline_elapsed"]])
  hash_match <- identical(this_hash, base_hash)
  cat(sprintf("BASELINE_HASH: %s\n", base_hash))
  cat(sprintf("BASELINE_ELAPSED: %.2f\n", base_el))
  cat(sprintf("HASH_MATCH: %s\n", hash_match))
  cat(sprintf("SPEEDUP: %.3fx\n", base_el / this_elapsed))
  if (!deterministic)
    cat("NOTE: non-deterministic output across runs — this is a correctness bug.\n")
} else {
  cat("BASELINE: (none — run with --capture first)\n")
}
