#!/usr/bin/env Rscript
# ============================================================================
# Secondary discovery speed bench — fixed-seed, bit-identical correctness gate.
#
# Purpose: give a `/goal` loop an unambiguous, reward-hack-resistant signal for
# behavior-preserving (Class A) speedups of the SECONDARY DISCOVERY tier — the
# pipeline stage (Tier 3B in inst/targets/_targets.R) that builds
# `discovered_secondary_library` from the parcel graph, parallel to the LCC
# discovery tier (Tier 3A) and using the SAME machinery: Wilson spanning-tree
# enumeration (discover_secondaries_from_trees) and BFS area-band growth
# (run_bfs_secondary_supplement -> bfs_grow_block), then the deterministic
# combine + library assembly (combine_discovered_blocks +
# build_secondary_library_from_discovery).
#
# This is the sibling of discovery_bench.R. The LCC tier was already sped up by
# converting bfs_grow_block to the integer fast path (bfs_build_context /
# bfs_grow_block_ctx); run_bfs_secondary_supplement still calls bfs_grow_block on
# the slow CHARACTER path (R/mcmc_parcel_library.R), so the same lever applies
# here and the fix already exists.
#
# This tier draws random numbers (tree sampling, BFS target areas via runif), so
# the gate is the SAME kind as the LCC discovery / MCMC sampler benches: under a
# fixed seed the whole discovery is reproducible, and a correct speedup LOWERS the
# time while keeping the output hash EQUAL to the captured baseline. The two runs
# must hash equal (DETERMINISTIC) or the bench FAILs.
#
# It loads a pre-built warm targets store (no gpkg / pipeline rebuild needed) for
# the one fixed input the discovery consumes — `parcel_graph_result` — then runs
# the full secondary discovery chain TWICE with a fixed seed and reports:
#   ELAPSED       min wall-clock of one full secondary-discovery run (s)
#   OUTPUT_HASH   rlang::hash of the discovered_secondary_library
#   HASH_MATCH    OUTPUT_HASH == baseline hash (the correctness gate)
#   SPEEDUP       baseline_elapsed / ELAPSED
#
# The pipeline runs tree enumeration and BFS supplement as separate targets; this
# bench runs them SERIALLY in one process under one seed. That is intentional: the
# bench defines its OWN baseline from current code — it does not need to match the
# pipeline's stored library, only to exercise the real discovery code and be
# internally reproducible. The serial single-seed draw sequence is the thing the
# Class A fence must preserve.
#
# Usage:
#   Rscript dev/bench/secondary_bench.R              # measure + compare to baseline
#   Rscript dev/bench/secondary_bench.R --capture    # (re)write secondary_baseline.txt
#
# DO NOT EDIT this file, secondary_baseline.txt, the seed, the store, or the
# secondary-discovery size constants in inst/targets/temp_targets_*.R while a speed
# goal is active — they define the measurement. The optimization target is the
# discovery implementation in R/mcmc_spanning_tree.R, R/mcmc_parcel_library.R, and
# R/mcmc_bfs_utils.R (but NOT the sample_spanning_tree draw itself).
# ============================================================================

suppressMessages({ library(targets); library(igraph) })

# --- fixed measurement parameters (treat as frozen) -------------------------
PKG_ROOT <- Sys.getenv("MBTAZONE_PACKAGE_ROOT",
  unset = "/home/dhidalgo/projects/mbtazone")
STORE    <- file.path(PKG_ROOT, "ext", "_targets_Topsfield")
SEED     <- 42L
RUNS     <- 2L         # repeats; ELAPSED = min, hashes must agree
BASELINE <- file.path(PKG_ROOT, "dev", "bench", "secondary_baseline.txt")

setwd(PKG_ROOT)
suppressMessages(pkgload::load_all(PKG_ROOT, quiet = TRUE,
                                   helpers = FALSE, attach_testthat = FALSE))
# Secondary-discovery size constants (size bands, n_trees, BFS quota, density
# threshold, library cap) arrive via the `discovery_spec` target loaded below —
# FROZEN inputs to the measurement, not rebuilt here.

stopifnot("warm store missing" = dir.exists(STORE))
tar_load(c(parcel_graph_result, discovery_spec, target_spec), store = STORE)

# --- one full secondary discovery (Tier 3B of inst/targets/_targets.R) -------
# Reproduces the target chain tree_discovered_secondaries ->
# bfs_discovered_secondaries -> combined_discovered_secondaries ->
# discovered_secondary_library, serially, under one seed.
run_once <- function() {
  set.seed(SEED)
  pg <- parcel_graph_result$parcel_graph

  # Stage 1: tree enumeration (Wilson's algorithm) — RNG
  tree_secs <- discover_secondaries_from_trees(
    parcel_graph      = pg,
    size_bands        = discovery_spec$sec_size_bands,
    density_threshold = discovery_spec$library_density_threshold,
    n_trees           = discovery_spec$tree_sec_n_trees,
    verbose           = FALSE
  )

  # Stage 2: BFS area-band supplement — RNG. This is where bfs_grow_block is on
  # the slow character path (the optimization target).
  bfs_secs <- run_bfs_secondary_supplement(
    tree_discovered_secondaries = tree_secs,
    parcel_graph                = pg,
    size_bands                  = discovery_spec$sec_size_bands,
    quota_per_band              = discovery_spec$bfs_sec_quota_per_band,
    density_threshold           = discovery_spec$library_density_threshold,
    verbose                     = FALSE
  )

  # Stage 3: combine tree + BFS discoveries — deterministic
  combined <- combine_discovered_blocks(
    tree_discovered = tree_secs,
    bfs_discovered  = bfs_secs,
    key_column      = "sec_key",
    block_type      = "secondary",
    verbose         = FALSE
  )

  # Stage 4: build secondary library — deterministic
  build_secondary_library_from_discovery(
    combined_discovered = combined,
    parcel_graph        = pg,
    max_library_size    = discovery_spec$sec_library_max_size,
    bfs_reservation     = discovery_spec$bfs_reservation_sec,
    constraints         = target_spec$constraints
  )
}

elapsed <- numeric(RUNS); hashes <- character(RUNS)
for (i in seq_len(RUNS)) {
  t <- system.time(s <- suppressMessages(run_once()))[["elapsed"]]
  elapsed[i] <- t; hashes[i] <- rlang::hash(s)
}

deterministic <- length(unique(hashes)) == 1L
this_elapsed  <- min(elapsed)
this_hash     <- hashes[[1]]

# --- capture mode: write baseline and exit ----------------------------------
args <- commandArgs(trailingOnly = TRUE)
if ("--capture" %in% args) {
  git_hash <- tryCatch(trimws(system("git rev-parse --short HEAD", intern = TRUE)),
                       error = function(e) "unknown")
  writeLines(c(
    sprintf("baseline_hash=%s", this_hash),
    sprintf("baseline_elapsed=%.3f", this_elapsed),
    sprintf("store=%s", basename(STORE)),
    sprintf("seed=%d", SEED),
    sprintf("git_commit=%s", git_hash)
  ), BASELINE)
  cat(sprintf("\nBASELINE CAPTURED -> %s\n", BASELINE))
  cat(sprintf("baseline_hash=%s\nbaseline_elapsed=%.3f\ndeterministic=%s\n",
              this_hash, this_elapsed, deterministic))
  quit(save = "no")
}

# --- compare mode -----------------------------------------------------------
base <- if (file.exists(BASELINE)) {
  kv <- strsplit(readLines(BASELINE), "=")
  setNames(vapply(kv, `[`, "", 2), vapply(kv, `[`, "", 1))
} else NULL

cat(sprintf("\n=== SECONDARY DISCOVERY SPEED BENCH (%s, seed=%d, runs=%d) ===\n",
            basename(STORE), SEED, RUNS))
cat(sprintf("ELAPSED: %.2f\n", this_elapsed))
cat(sprintf("OUTPUT_HASH: %s\n", this_hash))
cat(sprintf("DETERMINISTIC: %s\n", deterministic))
if (!is.null(base)) {
  base_hash <- base[["baseline_hash"]]; base_el <- as.numeric(base[["baseline_elapsed"]])
  hash_match <- identical(this_hash, base_hash)
  cat(sprintf("BASELINE_HASH: %s\n", base_hash))
  cat(sprintf("BASELINE_ELAPSED: %.2f\n", base_el))
  cat(sprintf("HASH_MATCH: %s\n", hash_match))
  cat(sprintf("SPEEDUP: %.3fx\n", base_el / this_elapsed))
  if (!deterministic)
    cat("NOTE: non-deterministic output across runs — this is a correctness bug.\n")
} else {
  cat("BASELINE: (none — run with --capture first)\n")
}
